"""Create clients and clients types tables

Revision ID: 4bc6c6a9d0b6
Revises: 
Create Date: 2024-09-29 17:47:08.494263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc6c6a9d0b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_entity_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('corporate_email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legal_entity_clients')
    op.drop_table('individual_clients')
    # ### end Alembic commands ###
